# Generated by Django 4.0.1 on 2022-08-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmate',
            old_name='task',
            new_name='addtask',
        ),
    ]
